version: 2.1

orbs:
  python: cjw296/python-ci@3

common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
{%- for version in cookiecutter.python_versions %}
              - circleci/cimg:{{ version }}
{%- endfor %}

    - python/coverage:
        name: coverage
        requires:
          - python/pip-run-tests

    - python/release:
        name: release
        config: .carthorse.yml
        requires:
          - coverage
        filters:
          branches:
            only: master

workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
